export const AnnotationTypes = {
    GET_ANNOTATION_REQUEST: "@admin/GET_ANNOTATION_REQUEST",
    GET_ANNOTATION_SUCCESS: "@admin/GET_ANNOTATION_SUCCESS",
    GET_ANNOTATION_ERROR: "@admin/GET_ANNOTATION_ERROR",
    ADD_ANNOTATION_PIC_REQUEST: "@admin/ADD_ANNOTATION_PIC_REQUEST",
    ADD_ANNOTATION_REQUEST: "@admin/ADD_ANNOTATION_REQUEST",
    ADD_ANNOTATION_SUCCESS: "@admin/ADD_ANNOTATION_SUCCESS",
    ADD_ANNOTATION_ERROR: "@admin/ADD_ANNOTATION_ERROR",
    UPDATE_ANNOTATION_REQUEST: "@admin/UPDATE_ANNOTATION_REQUEST",
    UPDATE_ANNOTATION_SUCCESS: "@admin/UPDATE_ANNOTATION_SUCCESS",
    UPDATE_ANNOTATION_ERROR: "@admin/UPDATE_ANNOTATION_ERROR",
    DELETE_ANNOTATION_REQUEST: "@admin/DELETE_ANNOTATION_REQUEST",
    DELETE_ANNOTATION_SUCCESS: "@admin/DELETE_ANNOTATION_SUCCESS",
    DELETE_ANNOTATION_ERROR: "@admin/DELETE_ANNOTATION_ERROR",
  };
  