export const UserTypes = {
  GET_USER_REQUEST: "@admin/GET_USER_REQUEST",
  GET_USER_SUCCESS: "@admin/GET_USER_SUCCESS",
  GET_USER_ERROR: "@admin/GET_USER_ERROR",

  LOGIN_USER_REQUEST: "@admin/LOGIN_USER_REQUEST",
  LOGIN_USER_SUCCESS: "@admin/LOGIN_USER_SUCCESS",
  LOGIN_USER_ERROR: "@admin/LOGIN_USER_ERROR",

  SET_USER_INFO: "@admin/SET_USER_INFO",
  RESET_USER_INFO: "@admin/RESET_USER_INFO",
};
